export default {
  pl: {
    yes: 'Tak',
    no: 'Nie',
    is: 'Jest',
    none: 'Brak',
    save: 'Zapisz',
    cancel: 'Anuluj',
    loading: 'Ładowanie',
    search: 'Szukaj',
    locationInfo: {
      fireAccess: 'Dostęp do ognia',
      waterAccess: 'Dostęp do wody',
      lastUpdate: 'Ostatnia aktualizacja',
    },
    locationType: {
      hut: 'Chatka',
      hutFireplace: 'Chatka z paleniskiem',
      shed: 'Wiata',
      waterSource: 'Źródło',
      cave: 'Jaskinia',
      pasture: 'Paśnik',
      pulpit: 'Ambona',
      tower: 'Wieża widokowa',
    },
    noResults: 'Nic nie znaleziono',
    markerForm: {
      heading: {
        addMarker: 'Dodaj nowe miejsce',
        editMarker: 'Edytuj miejsce',
      },
      location: 'Położenie geograficzne',
      place: 'Nazwa miejsca',
      type: 'Typ miejsca',
      description: 'Opis miejsca',
      waterDescription: 'Opis dostępu do wody (opcjonalnie)',
      fireDescription: 'Opis dostępu do ognia (opcjonalnie)',
    },
    notifications: {
      markerUpdated: 'Marker zaktualizowany.',
      newMarkerAdded: 'Dodano nowy marker.',
      couldNotSaveMarker: 'Nie udało się zapisać markera.',
      photoAdded: 'Dodano nowe zdjęcie.',
      couldNotSavePhoto: 'Nie udało się zapisać zdjęcia.',
    },
    actions: {
      edit: 'Edytuj',
      addPhoto: 'Dodaj zdjęcie',
    },
    addMarker: 'Dodaj miejsce',
    auth: {
      loginSuccessful: 'Zalogowano pomyślnie',
      login: 'Logowanie',
      logout: 'Wyloguj',
    },
  },

  en: {
    yes: 'Yes',
    no: 'No',
    is: 'Is available',
    none: 'None',
    cancel: 'Cancel',
    loading: 'Loading',
    search: 'Search',
    locationInfo: {
      fireAccess: 'Access to fire',
      waterAccess: 'Access to water',
      lastUpdate: 'Last update',
    },
    locationType: {
      hut: 'Hut',
      hutFireplace: 'Hut with a fireplace',
      shed: 'Shed',
      waterSource: 'Water source',
      cave: 'Cave',
      pasture: 'Pasture',
      pulpit: 'Pulpit',
      tower: 'Observation Tower',
    },
    noResults: 'No results',
    markerForm: {
      heading: {
        addMarker: 'Add new place',
        editMarker: 'Edit place',
      },
      location: 'Coordinates',
      place: 'Name of the place',
      type: 'Type of the place',
      description: 'Description',
      waterDescription: 'Access to water description (optional)',
      fireDescription: 'Access to fire description (optional)',
    },
    notifications: {
      markerUpdated: 'Marker updated.',
      newMarkerAdded: 'New marker added.',
      couldNotSaveMarker: 'Could not save a marker.',
      photoAdded: 'Photo added.',
      couldNotSavePhoto: 'Could not save a photo.',
    },
    actions: {
      edit: 'Edit',
      addPhoto: 'Add photo',
    },
    addMarker: 'Add place',
    auth: {
      loginSuccessful: 'Login successful',
      login: 'Login',
      logout: 'Logout',
    },
  },
}
