export default {
  pl: {
    yes: 'Tak',
    no: 'Nie',
    is: 'Jest',
    none: 'Brak',
    cancel: 'Anuluj',
    locationInfo: {
      fireAccess: 'Dostęp do ognia',
      waterAccess: 'Dostęp do wody',
      lastUpdate: 'Ostatnia aktualizacja',
    },
    noResults: 'Nic nie znaleziono',
    markerForm: {
      heading: {
        addMarker: 'Dodaj nowe miejsce',
        editMarker: 'Edytuj miejsce',
      },
      location: 'Położenie',
      place: 'Nazwa miejsca',
      type: 'Typ miejsca',
      description: 'Opis miejsca',
      coordinates: 'Współrzędne geograficzne',
      waterDescription: 'Opis dostępu do wody (opcjonalnie)',
      fireDescription: 'Opis dostępu do ognia (opcjonalnie)',
      upload: 'Wgraj zdjęcie',
      uploadDescription: 'Przeciągnij i upuść plik tutaj lub kliknij aby wybrać',
      cta: 'Zapisz',
      thankYouHeading: 'Dzięki!',
      thankYouMessage: 'Punkt został dodany i będzie widoczny po akceptacji moderatora.',
    },
    markerUpdated: 'Marker zaktualizowany.',
    newMarkerAdded: 'Dodano nowy marker.',
    couldNotSaveMarker: 'Nie udało się zapisać markera.',
    photoAdded: 'Dodano nowe zdjęcie.',
    couldNotSavePhoto: 'Nie udało się zapisać zdjęcia.',
    actions: {
      edit: 'Edytuj',
      addPhoto: 'Dodaj zdjęcie',
    },
    map: {
      loading: 'Ładowanie mapy...',
      add: 'Dodaj miejsce',
    },
    auth: {
      welcome: 'Witaj',
      login: 'Logowanie',
      logout: 'Wyloguj',
      fbLogin: 'Zaloguj Facebookiem',
      googleLogin: 'Zaloguj z Google',
    },
  },
  en: {
    yes: 'Yes',
    no: 'No',
    is: 'Is available',
    none: 'None',
    cancel: 'Cancel',
    locationInfo: {
      fireAccess: 'Access to fire',
      waterAccess: 'Access to water',
    },
    noResults: 'No results',
    markerForm: {
      heading: {
        addMarker: 'Dodaj nowe miejsce',
        editMarker: 'Edytuj miejsce',
      },
      location: 'Położenie',
      place: 'Nazwa miejsca',
      type: 'Typ miejsca',
      description: 'Opis miejsca',
      coordinates: 'Współrzędne geograficzne',
      waterDescription: 'Opis dostępu do wody (opcjonalnie)',
      fireDescription: 'Opis dostępu do ognia (opcjonalnie)',
      upload: 'Wgraj zdjęcie',
      uploadDescription: 'Przeciągnij i upuść plik tutaj lub kliknij aby wybrać',
      cta: 'Zapisz',
      thankYouHeading: 'Dzięki!',
      thankYouMessage: 'Punkt został dodany i będzie widoczny po akceptacji moderatora.',
    },
    marker: {
      waterAccess: 'Dostęp do wody',
      fireAccess: 'Dostęp do ognia',
    },
    markerUpdated: 'Marker zaktualizowany.',
    newMarkerAdded: 'Dodano nowy marker.',
    couldNotSaveMarker: 'Nie udało się zapisać markera.',
    photoAdded: 'Dodano nowe zdjęcie.',
    couldNotSavePhoto: 'Nie udało się zapisać zdjęcia.',
    actions: {
      edit: 'Edytuj',
      addPhoto: 'Dodaj zdjęcie',
    },
    map: {
      loading: 'Ładowanie mapy...',
      add: 'Dodaj miejsce',
    },
    auth: {
      welcome: 'Witaj',
      login: 'Logowanie',
      logout: 'Wyloguj',
      fbLogin: 'Zaloguj Facebookiem',
      googleLogin: 'Zaloguj z Google',
    },
  },
}
